REM INSERTING into EXPORT_TABLE
SET DEFINE OFF;
Insert into EXPORT_TABLE (CUSTOMERID,CUSTOMERFNAME,CUSTOMERLNAME) values (1,'Pawan','patil');
Insert into EXPORT_TABLE (CUSTOMERID,CUSTOMERFNAME,CUSTOMERLNAME) values (2,'sanjeev','patel');
Insert into EXPORT_TABLE (CUSTOMERID,CUSTOMERFNAME,CUSTOMERLNAME) values (3,'sanjay','shah');
Insert into EXPORT_TABLE (CUSTOMERID,CUSTOMERFNAME,CUSTOMERLNAME) values (4,'aditya','sharma');
Insert into EXPORT_TABLE (CUSTOMERID,CUSTOMERFNAME,CUSTOMERLNAME) values (5,'vivek','satya');
